const products = [
    {
        _id: '1',
        name: '4-pieces Shoulder Bag',
        image: './images/4Pcsbag.jpg',
        description: 'This piece comprises of glasses pouch, clutch bag, bucket bag and shoulder bag. It is very affordable and allows for change in size per occassion',
        brand: 'Dior',
        category: 'Fashion',
        price: 11000,
        countInStock: 4,
        rating: 4.5,
        numReviews: 5,
    },
    {
        _id: '2',
        name: 'Boss Lady Top',
        image: './images/boss.jpg',
        description: 'This piece comprises of glasses pouch, clutch bag, bucket bag and shoulder bag. It is very affordable and allows for change in size per occassion',
        brand: 'Fendi',
        category: 'Fashion',
        price: 6500,
        countInStock: 4,
        rating: 4.5,
        numReviews: 11,
    },
    {
        _id: '3',
        name: 'Ladies Canvas',
        image: './images/canvas.jpg',
        description: 'This piece comprises of glasses pouch, clutch bag, bucket bag and shoulder bag. It is very affordable and allows for change in size per occassion',
        brand: 'Nike',
        category: 'Fashion',
        price: 7000,
        countInStock: 4,
        rating: 4,
        numReviews: 8,
    },
    {
        _id: '4',
        name: 'Baby Girl Ball Dress',
        image: './images/babygirl.jpg',
        description: 'This piece comprises of glasses pouch, clutch bag, bucket bag and shoulder bag. It is very affordable and allows for change in size per occassion',
        brand: 'Versace',
        category: 'Fashion',
        price: 15000,
        countInStock: 4,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '5',
        name: 'Stock Denim Jeans',
        image: './images/denim.jpg',
        description: 'This piece comprises of glasses pouch, clutch bag, bucket bag and shoulder bag. It is very affordable and allows for change in size per occassion',
        brand: 'Dior',
        category: 'Fashion',
        price: 9000,
        countInStock: 4,
        rating: 5,
        numReviews: 6,
    },
    {
        _id: '6',
        name: 'Ladies heeled shoe',
        image: './images/silhouette1.jpg',
        description: 'This piece comprises of glasses pouch, clutch bag, bucket bag and shoulder bag. It is very affordable and allows for change in size per occassion',
        brand: 'Dior',
        category: 'Fashion',
        price: 12000,
        countInStock: 4,
        rating: 4,
        numReviews: 7,
    },
    {
        _id: '7',
        name: 'Baby Girl Ball Gown',
        image: './images/balldress.jpg',
        description: 'This piece comprises of glasses pouch, clutch bag, bucket bag and shoulder bag. It is very affordable and allows for change in size per occassion',
        brand: 'Dior',
        category: 'Fashion',
        price: 9500,
        countInStock: 4,
        rating: 4,
        numReviews: 6,
    },
    {
        _id: '8',
        name: 'Summer Baby Boy Set',
        image: './images/boysuit.jpg',
        description: 'This piece comprises of glasses pouch, clutch bag, bucket bag and shoulder bag. It is very affordable and allows for change in size per occassion',
        brand: 'Dior',
        category: 'Fashion',
        price: 4500,
        countInStock: 4,
        rating: 4,
        numReviews: 4,
    }
]

export default products